### ISSUE TITLE
missing option in font config

### ISSUE THREAD

**Issue by xplosions** [tonipinel/frontendcore-workspace#8]
$font-line-height-custom: (
		base: 1.5em,
		title: 1.2em
) !global !default;

I expect to have there the weight

**Comment by tonipinel** [comment]
Ok, I'm going to publish a new version with this solved, but take care because I also refactor de font maps and unified them. Please delete the old 3 custom maps and replace it with this (customizing it of course)

$fonts-custom: (
		line-height-base: 1.5em,
		line-height-title: 1.2em,
		face-default: "'Helvetica Neue', Helvetica, Helvetica, Arial, sans-serif",
		face-title: "'Open Sans Condensed','Arial Narrow', Tahoma, sans-serif",
		weight-default: normal,
		weight-title: bold,
		icons: true,
		size-base: 15px,
		size-xxxl: 2.2rem,
		size-xxl: 1.7rem,
		size-xl: 1.4rem,
		size-l: 1.3rem,
		size-ml: 1.2rem,
		size-m: 1.1rem,
		size-default: 1rem,
		size-s: .9rem,
		size-xs: .8rem,
		size-xxs: .75rem,
		size-xxxs: .7rem,
		size-xxxxs: .6rem,
		size-title-exponential: 1.5
) !global !default;

**Comment by xplosions** [comment]
Awesome!! Thx ;D
